font_size 14.0
action_alias launch_tab launch --cwd=current --type=tab
map f1 launch_tab
map f2 launch_tab "nvim ."
map f3 launch --cwd=current "nohup dolphin . "
map f5 launch --cwd=current --type=os-window
